import type { FineRule, Radar, VehicleSettings } from '../types.js'

/** Seeds alinhados às migrations 009 / 010 — usados pelo DemoStore. */

export const SEED_FINE_RULES: Omit<FineRule, 'id'>[] = [
  {
    code: 'ctb_218_i',
    severity: 'media',
    article: 'CTB art. 218, I',
    excessMinPct: 0,
    excessMaxPct: 20,
    fineBrl: 130.16,
    points: 4,
    suspendRight: false,
    description:
      'Transitar em velocidade superior à máxima permitida em até 20% — estimativa de possível infração',
    active: true,
  },
  {
    code: 'ctb_218_ii',
    severity: 'grave',
    article: 'CTB art. 218, II',
    excessMinPct: 20,
    excessMaxPct: 50,
    fineBrl: 195.23,
    points: 5,
    suspendRight: false,
    description:
      'Transitar em velocidade superior à máxima permitida em mais de 20% até 50% — estimativa de possível infração',
    active: true,
  },
  {
    code: 'ctb_218_iii',
    severity: 'gravissima',
    article: 'CTB art. 218, III',
    excessMinPct: 50,
    excessMaxPct: null,
    fineBrl: 880.41,
    points: 7,
    suspendRight: true,
    description:
      'Transitar em velocidade superior à máxima permitida em mais de 50% — estimativa de possível infração',
    active: true,
  },
]

export const SEED_DEMO_RADARS: Omit<Radar, 'id'>[] = [
  {
    externalId: 'r1',
    name: 'Radar Consolação',
    cameraType: 'fixed',
    lat: -23.5595,
    lng: -46.6508,
    speedLimitKmh: 50,
    directionDeg: 70,
    directionToleranceDeg: 60,
    alertRadiusM: 220,
    passRadiusM: 55,
    roadName: 'Consolação',
    city: 'São Paulo',
    state: 'SP',
    source: 'demo',
    active: true,
  },
  {
    externalId: 'r2',
    name: 'Radar Augusta',
    cameraType: 'fixed',
    lat: -23.5558,
    lng: -46.6435,
    speedLimitKmh: 50,
    directionDeg: 70,
    directionToleranceDeg: 60,
    alertRadiusM: 220,
    passRadiusM: 55,
    roadName: 'Augusta',
    city: 'São Paulo',
    state: 'SP',
    source: 'demo',
    active: true,
  },
  {
    externalId: 'r3',
    name: 'Radar Higienópolis',
    cameraType: 'fixed',
    lat: -23.5518,
    lng: -46.6345,
    speedLimitKmh: 40,
    directionDeg: 70,
    directionToleranceDeg: 60,
    alertRadiusM: 200,
    passRadiusM: 50,
    roadName: 'Higienópolis',
    city: 'São Paulo',
    state: 'SP',
    source: 'demo',
    active: true,
  },
  {
    externalId: 'r4',
    name: 'Radar Pacaembu',
    cameraType: 'fixed',
    lat: -23.5497,
    lng: -46.6235,
    speedLimitKmh: 60,
    directionDeg: 90,
    directionToleranceDeg: 60,
    alertRadiusM: 250,
    passRadiusM: 60,
    roadName: 'Pacaembu',
    city: 'São Paulo',
    state: 'SP',
    source: 'demo',
    active: true,
  },
  {
    externalId: 'r5',
    name: 'Radar Sumaré',
    cameraType: 'fixed',
    lat: -23.5508,
    lng: -46.6125,
    speedLimitKmh: 50,
    directionDeg: 100,
    directionToleranceDeg: 60,
    alertRadiusM: 220,
    passRadiusM: 55,
    roadName: 'Sumaré',
    city: 'São Paulo',
    state: 'SP',
    source: 'demo',
    active: true,
  },
]

export const SEED_VEHICLE_SETTINGS: Omit<VehicleSettings, 'id'> = {
  label: 'default',
  fuelPriceBrl: 6.5,
  fuelEconomyKmPerL: 10,
  vehicleType: 'car',
  includeTolls: true,
}
