import type { FineRule, Radar, VehicleSettings } from '../types.js'
import type { RoadSegment } from '../engines/MapMatching.js'

/** Seeds alinhados às migrations 009 / 010 — usados pelo DemoStore. */

export const SEED_FINE_RULES: Omit<FineRule, 'id'>[] = [
  {
    code: 'ctb_218_i',
    severity: 'media',
    article: 'CTB art. 218, I',
    excessMinPct: 0,
    excessMaxPct: 20,
    fineBrl: 130.16,
    points: 4,
    suspendRight: false,
    description:
      'Transitar em velocidade superior à máxima permitida em até 20% — estimativa de possível infração',
    active: true,
  },
  {
    code: 'ctb_218_ii',
    severity: 'grave',
    article: 'CTB art. 218, II',
    excessMinPct: 20,
    excessMaxPct: 50,
    fineBrl: 195.23,
    points: 5,
    suspendRight: false,
    description:
      'Transitar em velocidade superior à máxima permitida em mais de 20% até 50% — estimativa de possível infração',
    active: true,
  },
  {
    code: 'ctb_218_iii',
    severity: 'gravissima',
    article: 'CTB art. 218, III',
    excessMinPct: 50,
    excessMaxPct: null,
    fineBrl: 880.41,
    points: 7,
    suspendRight: true,
    description:
      'Transitar em velocidade superior à máxima permitida em mais de 50% — estimativa de possível infração',
    active: true,
  },
]

export const SEED_DEMO_RADARS: Omit<Radar, 'id'>[] = [
  {
    externalId: 'r1',
    name: 'Radar Consolação',
    cameraType: 'fixed',
    lat: -23.5595,
    lng: -46.6508,
    speedLimitKmh: 50,
    directionDeg: 70,
    directionToleranceDeg: 60,
    alertRadiusM: 220,
    passRadiusM: 55,
    roadName: 'Consolação',
    city: 'São Paulo',
    state: 'SP',
    source: 'demo',
    active: true,
  },
  {
    externalId: 'r2',
    name: 'Radar Augusta',
    cameraType: 'fixed',
    lat: -23.5558,
    lng: -46.6435,
    speedLimitKmh: 50,
    directionDeg: 70,
    directionToleranceDeg: 60,
    alertRadiusM: 220,
    passRadiusM: 55,
    roadName: 'Augusta',
    city: 'São Paulo',
    state: 'SP',
    source: 'demo',
    active: true,
  },
  {
    externalId: 'r3',
    name: 'Radar Higienópolis',
    cameraType: 'fixed',
    lat: -23.5518,
    lng: -46.6345,
    speedLimitKmh: 40,
    directionDeg: 70,
    directionToleranceDeg: 60,
    alertRadiusM: 200,
    passRadiusM: 50,
    roadName: 'Higienópolis',
    city: 'São Paulo',
    state: 'SP',
    source: 'demo',
    active: true,
  },
  {
    externalId: 'r4',
    name: 'Radar Pacaembu',
    cameraType: 'fixed',
    lat: -23.5497,
    lng: -46.6235,
    speedLimitKmh: 60,
    directionDeg: 90,
    directionToleranceDeg: 60,
    alertRadiusM: 250,
    passRadiusM: 60,
    roadName: 'Pacaembu',
    city: 'São Paulo',
    state: 'SP',
    source: 'demo',
    active: true,
  },
  {
    externalId: 'r5',
    name: 'Radar Sumaré',
    cameraType: 'fixed',
    lat: -23.5508,
    lng: -46.6125,
    speedLimitKmh: 50,
    directionDeg: 100,
    directionToleranceDeg: 60,
    alertRadiusM: 220,
    passRadiusM: 55,
    roadName: 'Sumaré',
    city: 'São Paulo',
    state: 'SP',
    source: 'demo',
    active: true,
  },
]

export const SEED_VEHICLE_SETTINGS: Omit<VehicleSettings, 'id'> = {
  label: 'default',
  fuelPriceBrl: 6.5,
  fuelEconomyKmPerL: 10,
  vehicleType: 'car',
  includeTolls: true,
}

/**
 * Segmentos OSM-like ao longo do trecho demo SP (piloto / matching local).
 * maxspeed_source = osm | local — sem API paga.
 */
export const SEED_ROAD_SEGMENTS: Omit<RoadSegment, 'id'>[] = [
  {
    osmWayId: 1001,
    name: 'Rua da Consolação',
    path: [
      { lat: -23.5614, lng: -46.6558 },
      { lat: -23.5602, lng: -46.6525 },
      { lat: -23.5588, lng: -46.6491 },
      { lat: -23.5571, lng: -46.6458 },
    ],
    oneway: 'both',
    forwardHeadingDeg: 72,
    maxspeedKmh: 50,
    maxspeedSource: 'osm',
    highwayClass: 'primary',
    confidence: 0.85,
    active: true,
  },
  {
    osmWayId: 1002,
    name: 'Rua Augusta',
    path: [
      { lat: -23.5571, lng: -46.6458 },
      { lat: -23.5554, lng: -46.6426 },
      { lat: -23.5539, lng: -46.6395 },
    ],
    oneway: 'both',
    forwardHeadingDeg: 75,
    maxspeedKmh: 50,
    maxspeedSource: 'osm',
    highwayClass: 'secondary',
    confidence: 0.8,
    active: true,
  },
  {
    osmWayId: 1003,
    name: 'Av. Higienópolis',
    path: [
      { lat: -23.5539, lng: -46.6395 },
      { lat: -23.5526, lng: -46.6362 },
      { lat: -23.5514, lng: -46.6328 },
      { lat: -23.5505, lng: -46.6291 },
    ],
    oneway: 'both',
    forwardHeadingDeg: 80,
    maxspeedKmh: 40,
    maxspeedSource: 'osm',
    highwayClass: 'secondary',
    confidence: 0.8,
    active: true,
  },
  {
    osmWayId: 1004,
    name: 'Av. Pacaembu',
    path: [
      { lat: -23.5505, lng: -46.6291 },
      { lat: -23.5499, lng: -46.6254 },
      { lat: -23.5496, lng: -46.6216 },
      { lat: -23.5498, lng: -46.6179 },
    ],
    oneway: 'both',
    forwardHeadingDeg: 90,
    maxspeedKmh: 60,
    maxspeedSource: 'local',
    highwayClass: 'primary',
    confidence: 0.9,
    active: true,
  },
  {
    osmWayId: 1005,
    name: 'Av. Sumaré',
    path: [
      { lat: -23.5498, lng: -46.6179 },
      { lat: -23.5504, lng: -46.6143 },
      { lat: -23.5515, lng: -46.6109 },
      { lat: -23.553, lng: -46.6078 },
    ],
    oneway: 'both',
    forwardHeadingDeg: 110,
    maxspeedKmh: 50,
    maxspeedSource: 'osm',
    highwayClass: 'primary',
    confidence: 0.8,
    active: true,
  },
]
